### PR TITLE
separate inline sprite from jquery.minicolors.css

### PR DESCRIPTION
**Pull request by hankmander**
If you want to avoid the added weight of the base64 image you could include only one of the two css files.

### CODE REVIEW

**Comment by markvantilburg** [comment]
In what kind of scenario do you use this?

**Comment by hankmander** [comment]
I set the dataUris option to false to fetch the external image. Then I
don't need the inline base64 version anymore. And since it's ~100kb big it
made a difference for me to remove it.

2015-01-05 14:40 GMT+01:00 mark van tilburg <notifications@github.com>:

**Comment by markvantilburg** [comment]
There seem to be issues with the data uri in Ie7 and Ie8, is that why you want to split it? Or do you need to support some obscure browse?

**Comment by hankmander** [comment]
For me it's a performance issue with an extra 100k css file. 95% of
jquery.minicolors.css is just the image.
Base64 encoded images are also really slow to load on mobile devices:
http://www.mobify.com/blog/data-uris-are-slow-on-mobile/

2015-01-05 15:06 GMT+01:00 mark van tilburg <notifications@github.com>:

**Comment by claviska** [comment]
The reason we moved to the data URIs was to prevent image references from getting broken. It also reduced the number of HTTP requests, but that's probably negligible in this case. For reference, the original discussion is located here: #140

At the time, my thinking was that all browsers (mobile or not) would use the data URIs and we'd simply provide a fallback for unsupportive browsers—performance wasn't really a huge concern considering that in either case the image still needs to be downloaded (whether as a PNG or as part of the CSS file).

We all know that base64 encoding adds some bloat. In this case, the original PNG is 77kb. The encoded data is about 104kb, so that's probably the biggest argument against using the sprite.

Unfortunately, this would be a breaking change and would force the project into 3.0. A better option would be to setup a build process that generates two CSS files—one with the sprite and one without. That would make the change backwards compatible and give you both options.

Of course, we may be making things more complicated than need be. Is the extra 27kb really worth the effort? I guess the answer really depends on your mobile network. Without turning this into a debate about mobile broadband speeds, [when I throttle the connection](http://www.elijahmanor.com/enhanced-chrome-emulation-tools/), I don't see much of a difference either way :-\

**Comment by hankmander** [comment]
Those are all valid points and maybe my usecase is not that big. You are
right that i have to download the image anyhow but I might not want to show
it on page load. In that case i can load the css on load but the image on
demand reducing the initial page load. Of course i could load the whole
css+sprite on demand instead but that is just trickier to do. I also
concatenate all css to one file in my build step and would have to leave
this css+sprite out of it somehow. I can see how you not want breaking
changes but having the option to include or not is nice. Maybe you can keep
it as it is now but create a new file called cssWithoutSprite.css for guys
like me? :)

2015-01-05 19:39 GMT+01:00 Cory LaViska <notifications@github.com>:

**Comment by claviska** [comment]
I'm not against it, I just prefer to keep things simple and adding another copy of the stylesheet for what seems to be an edge case feels like bloat :)

To be honest, given the size difference of the image compared to the data URI, I'd almost prefer to go back to using the separate image (probably in 3.0). You made a point about loading the image on demand, and the browser will in fact do just that with the separate image since it's not shown right away (unless you're using an inline control). With the data URI, it's forced to load the entire thing.

In hindsight, I think the reasons to stick with a separate image outweigh the data URI:

Pros:
- Automatically loaded by browser on demand and only if needed
- Smaller size because it's not [base64] encoded
- Easier to maintain (if the image changes, doesn't need to be regenerated, and different methods provide different compression rates)

Cons:
- Could potentially cause problems with relative URLs if styles are included into a project. (For what it's worth, I use CodeKit and I've never had this problem.)

Am I missing anything else?

There are a couple features that I've been wanting to get done for 3.0, and I think going back to using the separate image will be a good move for that version.

**Comment by markvantilburg** [comment]
I would agree to removing the base encoded version, as only newer browsers support it but there you could also just use the color input type.

**Comment by hankmander** [comment]
I think you have all the points in your list. Thanks for listening! :)

2015-01-07 22:08 GMT+01:00 mark van tilburg <notifications@github.com>:

**Comment by pbougie** [comment]
I recently converted my front-end assets to Bower which updated jQuery MiniColors at the same time (I was running an old version with a linked image). Much to my dismay, my CSS file grew by 91KB! This is not optimal since about 5% of my users, 1% of the time need the color picker in my app. I've since had to manually include the library and edit the CSS file by hand to remove the sprite and link to the image. It would be great if we could find a solution to this.

**Comment by claviska** [comment]
Data URIs will be removed in 3.0. Follow #217 for details.

**Pull request closed without merging**
