### PR TITLE
Add a package.json for installing via npm

### PR DESCRIPTION
**Pull request by twalker**
Please add a `package.json` file for installing this fine plugin via npm.

### CODE REVIEW

**Comment by spathon** [comment]
:+1:

**Comment by claviska** [comment]
If you submit a PR for it, I'll keep it updated for future versions. As it is, I have bower.json, component.json, composer.json, and I only sometimes use one of them. Wish we could combine them someone.

**Comment by twalker** [comment]
I believe this is a PR for adding a package.json file, and it probably can be automatically merged within github. Let me know if you need a fresh PR.

I too, grow tired of the fragmentation of package managers.

**Comment by claviska** [comment]
Ha, sorry. Got caught up in issues and PRs and mistook this one for an issue. Will merge soon and bump version. Thanks. 






— Cory LaViska




A Beautiful Site, LLC

www.abeautifulsite.net

**Pull request merged**
