### PR TITLE
Add support for 8-bit RGB

### PR DESCRIPTION
**Pull request by renholm**
Hi,

What you you think about this change? We wanted to make it easier for non technical people to input colors without picking them. 

I think we've managed to cover most cases, but maybe there some caveats we've been unaware of?

/K

### CODE REVIEW

**Comment by claviska** [comment]
@JoomliC is working on something very similar in #170 which I've already left feedback for. Note sure of the timeline for that but he may be nearing completion so I'd like to hear from him first :)

**Comment by renholm** [comment]
@claviska Looked into #170 and to it seems to add quite a lot of other things as well. This PR is purely to get something else into the text box than hex, everything else is working the same. To get the `rgba` string mentioned in #170 we are using the already existing method `rgbaString`.

**Comment by claviska** [comment]
Thanks again for contributing. #170 has been accepted for proper RGB(A) support, so I won't be merging this. I do like the approach though :)

**Comment by claviska** [comment]
Maybe something for the wish list: ability to specify a custom formatting/parsing function so you could have any input/output you like :)

**Pull request closed without merging**
