### PR TITLE
typeof test for rgba[3]

### PR DESCRIPTION
**Pull request by harisrozak**

### CODE REVIEW

**Comment by claviska** [comment]
Good call on this. I clearly missed the `typeof` check on the same line. I blame it being late ;)

**Comment by harisrozak** [comment]
I'm happy to help :)

**Comment by JoomliC** [comment]
Great!
Thank you :+1: 

So, @claviska when do you think you will be able to release officially ?

**Comment by claviska** [comment]
Already has. Thanks so much for your work on this!

**Comment by JoomliC** [comment]
@claviska Great!
I thought not yet officially, as the demo page not updated... ;-)

Thank you for your help in making it possible! Will soon update my PR for Joomla!, to integrate it in this CMS !
(and curious about your Particle project ;-) )

**Comment by claviska** [comment]
Whoops. I always forget to update the demo. This project could really benefit from a real build process ;)

And yes, Particle. I'm making excellent progress. Follow [@particlecms](http://twitter.com/particlecms) for day to day updates. If you want to help beta test get on the [mailing list](http://www.particlecms.com/) soon :)

**Comment by claviska** [comment]
FYI, demo has been updated.

**Comment by JoomliC** [comment]
<blockquote>And yes, Particle. I'm making excellent progress. Follow @particlecms for day to day updates. If you want to help beta test get on the mailing list soon :)</blockquote>
Already did ;-)

Thank you for all your help in making those new functionalities possible! :+1:

**Pull request merged**
